export const blogPosts = [
    {
        topic: "firebase",
        title: "Firebase-1",
        name: "firebase-1",
        logoName: "firebase-logo",
        createDate: "03 March 2022",
        key: "1",
    },
    {
        topic: "typescript",
        title: "useState hook with Typescript",
        name: "typescript-1",
        logoName: "typescript-logo",
        createDate: "04 March 2022",
        key: "2",
    },
    {
        topic: "typescript",
        title: "useEffect hook with Typescript",
        name: "typescript-2",
        logoName: "typescript-logo",
        createDate: "06 March 2022",
        key: "3",
    },
    {
        topic: "javascript",
        title: "Array methods of Javascript",
        name: "javascript-1",
        logoName: "javascript-logo",
        createDate: "07 March 2022",
        key: "4",
    },
    {
        topic: "react",
        title: "React Context and useContext() Hook",
        name: "useContext",
        logoName: "react-logo",
        createDate: "08 March 2022",
        key: "5",
    },
];
